export enum Action {
  EDITING = 'EDITING',
  EDIT_DONE = 'EDIT_DONE',
  EDIT_START = 'EDIT_START',
  MOVE = 'MOVE',
  NON_EDIT = 'NON_EDIT',
  RENAME = 'RENAME',
  RESTORE = 'RESTORE',
  THROW = 'THROW',
}
